import { Router } from 'express';
import type { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { requireAuth } from '../../middleware/auth.js';
import { operationalActor, requirePermission, requireDriver, operationalDriverScope, fleetScope, deny, can, type OperationalPermission, type OperationalActor } from './operationalPolicy.js';
import { saveTruckInTransaction, publicTruck } from '../trucks/profileRevision.js';
export const operationalRouter=Router();operationalRouter.use(requireAuth);
const wrap=(fn:(req:any,res:any)=>Promise<unknown>)=>(req:any,res:any,next:any)=>{Promise.resolve(fn(req,res)).catch(next);};
const id=z.string().min(1).max(128);const reason=z.string().trim().min(5).max(500);const revision=z.number().int().positive();
async function actor(tx:Prisma.TransactionClient,userId:string,permission:OperationalPermission){const user=await tx.user.findUnique({where:{id:userId},select:{id:true,role:true,disabledAt:true}});if(!user||user.disabledAt)deny();const a=await operationalActor(tx,{userId:user.id,role:user.role});requirePermission(a,permission);return a;}
async function mutate(userId:string,permission:OperationalPermission,fn:(tx:Prisma.TransactionClient,a:OperationalActor)=>Promise<unknown>){return prisma.$transaction(async tx=>fn(tx,await actor(tx,userId,permission)),{isolationLevel:'Serializable'});}
async function audit(tx:Prisma.TransactionClient,a:OperationalActor,action:string,targetType:string,targetId:string,why:string,before:unknown,after:unknown){await tx.adminAuditLog.create({data:{actorUserId:a.userId,action,targetType,targetId,metadataJson:JSON.parse(JSON.stringify({reason:why,before,after}))}});}
async function ownedFleet(tx:Prisma.TransactionClient,a:OperationalActor,fleetId:string){const fleet=await tx.operationalFleet.findFirst({where:{AND:[{id:fleetId,active:true},fleetScope(a)]}});if(!fleet)deny('RECORD_NOT_FOUND',404);return fleet;}
operationalRouter.get('/capabilities',wrap(async(req,res)=>{const a=await operationalActor(prisma,req.user);const permissions:OperationalPermission[]=['drivers.read','drivers.manage','trucks.read','trucks.edit','equipment.read','equipment.manage','dispatch.read','dispatch.manage','support.read','support.manage','notifications.send','billing.read','roles.manage','audit.read'];res.json({role:a.role,globalScope:a.globalScope,fleetIds:a.fleetIds,permissions:permissions.filter(p=>can(a,p))});}));
operationalRouter.get('/drivers',wrap(async(req,res)=>{const a=await actor(prisma,req.user.userId,'drivers.read');res.json({items:await prisma.user.findMany({where:{AND:[operationalDriverScope(a),{staffAccess:null}]},select:{id:true,fullName:true,email:true,disabledAt:true},orderBy:{id:'asc'},take:100})});}));
operationalRouter.get('/drivers/:id/trucks',wrap(async(req,res)=>{const a=await actor(prisma,req.user.userId,'trucks.read');const driver=id.parse(req.params.id);await requireDriver(prisma,a,driver);res.json({items:(await prisma.truck.findMany({where:{userId:driver},orderBy:{updatedAt:'desc'},take:100})).map(publicTruck)});}));
operationalRouter.patch('/drivers/:id',wrap(async(req,res)=>{const driver=id.parse(req.params.id);const body=z.object({disabled:z.boolean(),reason}).strict().parse(req.body);res.json(await mutate(req.user.userId,'drivers.manage',async(tx,a)=>{await requireDriver(tx,a,driver);const before=await tx.user.findUniqueOrThrow({where:{id:driver},select:{disabledAt:true}});const after=await tx.user.update({where:{id:driver},data:{disabledAt:body.disabled?new Date():null},select:{id:true,disabledAt:true}});if(body.disabled)await tx.refreshToken.updateMany({where:{userId:driver,revokedAt:null},data:{revokedAt:new Date()}});await audit(tx,a,'DRIVER_ACCESS_UPDATED','USER',driver,body.reason,before,after);return after;}));}));
operationalRouter.patch('/drivers/:id/trucks/:truckId',wrap(async(req,res)=>{const driver=id.parse(req.params.id);const truckId=id.parse(req.params.truckId);const body=z.object({expectedRevision:revision,reason,profile:z.record(z.unknown())}).strict().parse(req.body);res.json(await mutate(req.user.userId,'trucks.edit',async(tx,a)=>{await requireDriver(tx,a,driver);return saveTruckInTransaction(tx,driver,a.userId,body.profile,truckId,body.expectedRevision,body.reason);}));}));
operationalRouter.get('/fleets',wrap(async(req,res)=>{const a=await actor(prisma,req.user.userId,'equipment.read');res.json({items:await prisma.operationalFleet.findMany({where:fleetScope(a),orderBy:{name:'asc'},take:100})});}));
operationalRouter.post('/fleets',wrap(async(req,res)=>{const body=z.object({name:z.string().trim().min(1).max(120),reason}).strict().parse(req.body);res.status(201).json(await mutate(req.user.userId,'roles.manage',async(tx,a)=>{if(!a.globalScope)deny();const fleet=await tx.operationalFleet.create({data:{name:body.name}});await audit(tx,a,'FLEET_CREATED','FLEET',fleet.id,body.reason,null,fleet);return fleet;}));}));
operationalRouter.post('/fleets/:id/drivers',wrap(async(req,res)=>{const fleetId=id.parse(req.params.id);const body=z.object({userId:id,active:z.boolean(),reason}).strict().parse(req.body);res.json(await mutate(req.user.userId,'roles.manage',async(tx,a)=>{if(!a.globalScope)deny();await ownedFleet(tx,a,fleetId);await requireDriver(tx,a,body.userId);const before=await tx.operationalFleetDriver.findUnique({where:{fleetId_userId:{fleetId,userId:body.userId}}});const after=await tx.operationalFleetDriver.upsert({where:{fleetId_userId:{fleetId,userId:body.userId}},create:{fleetId,userId:body.userId,active:body.active},update:{active:body.active}});if(!body.active)await tx.equipment.updateMany({where:{fleetId,assignedDriverId:body.userId},data:{assignedDriverId:null,revision:{increment:1}}});await audit(tx,a,'FLEET_DRIVER_UPDATED','FLEET',fleetId,body.reason,before,after);return after;}));}));
operationalRouter.get('/equipment',wrap(async(req,res)=>{const a=await actor(prisma,req.user.userId,'equipment.read');res.json({items:await prisma.equipment.findMany({where:{fleet:{AND:[{active:true},fleetScope(a)]}},orderBy:{updatedAt:'desc'},take:100})});}));
operationalRouter.post('/equipment',wrap(async(req,res)=>{const body=z.object({fleetId:id,kind:z.enum(['TRACTOR','TRAILER']),name:z.string().trim().min(1).max(120),unitNumber:z.string().trim().min(1).max(40),reason}).strict().parse(req.body);res.status(201).json(await mutate(req.user.userId,'equipment.manage',async(tx,a)=>{await ownedFleet(tx,a,body.fleetId);const {reason:why,...data}=body;const after=await tx.equipment.create({data});await audit(tx,a,'EQUIPMENT_CREATED','EQUIPMENT',after.id,why,null,after);return after;}));}));
operationalRouter.patch('/equipment/:id',wrap(async(req,res)=>{const equipmentId=id.parse(req.params.id);const body=z.object({expectedRevision:revision,assignedDriverId:id.nullable(),active:z.boolean(),reason}).strict().parse(req.body);res.json(await mutate(req.user.userId,'equipment.manage',async(tx,a)=>{const before=await tx.equipment.findFirst({where:{id:equipmentId,fleet:fleetScope(a)}});if(!before)deny('RECORD_NOT_FOUND',404);await ownedFleet(tx,a,before.fleetId);if(before.revision!==body.expectedRevision)deny('RECORD_CHANGED',409);if(body.assignedDriverId){await requireDriver(tx,a,body.assignedDriverId);const member=await tx.operationalFleetDriver.findFirst({where:{fleetId:before.fleetId,userId:body.assignedDriverId,active:true}});if(!member||!body.active)deny();}const after=await tx.equipment.update({where:{id:equipmentId},data:{assignedDriverId:body.assignedDriverId,active:body.active,revision:{increment:1}}});await audit(tx,a,'EQUIPMENT_UPDATED','EQUIPMENT',equipmentId,body.reason,before,after);return after;}));}));
operationalRouter.post('/staff/:id',wrap(async(req,res)=>{const userId=id.parse(req.params.id);const body=z.object({role:z.enum(['SUPER_ADMIN','OPERATIONS','DISPATCH','SAFETY','SUPPORT','BILLING','READ_ONLY']),globalScope:z.boolean(),fleetIds:z.array(id).max(100),reason}).strict().parse(req.body);res.json(await mutate(req.user.userId,'roles.manage',async(tx,a)=>{if(!a.globalScope||userId===a.userId)deny();const user=await tx.user.findUnique({where:{id:userId},select:{role:true,disabledAt:true}});if(!user||user.disabledAt||user.role==='ADMIN')deny();if(body.role==='SUPER_ADMIN')deny();const unique=[...new Set(body.fleetIds)];if(await tx.operationalFleet.count({where:{id:{in:unique},active:true}})!==unique.length)deny();const before=await tx.staffAccess.findUnique({where:{userId},include:{fleets:true}});const after=await tx.staffAccess.upsert({where:{userId},create:{userId,role:body.role,globalScope:body.globalScope},update:{role:body.role,globalScope:body.globalScope}});await tx.staffFleetAccess.deleteMany({where:{staffAccessId:after.id}});await tx.staffFleetAccess.createMany({data:unique.map(fleetId=>({fleetId,staffAccessId:after.id}))});await tx.refreshToken.updateMany({where:{userId,revokedAt:null},data:{revokedAt:new Date()}});await audit(tx,a,'STAFF_ACCESS_UPDATED','USER',userId,body.reason,before,{...after,fleetIds:unique});return {id:after.id,role:after.role};}));}));
