import { useEffect, useState } from 'react';
import { api } from './api';
type Driver={id:string;fullName:string;email:string;disabledAt:string|null};
type Fleet={id:string;name:string};
type Equipment={id:string;fleetId:string;name:string;unitNumber:string;kind:string;revision:number;active:boolean;assignedDriverId:string|null};
type Truck=Record<string,unknown>&{id:string;name:string;revision:number;verificationState:string};
const fields=[['name','Profile name','text'],['tractorType','Tractor type','text'],['trailerType','Trailer type','text'],['unitNumber','Unit number','text'],['trailerNumber','Trailer number','text'],['heightFt','Height (decimal feet)','number'],['widthFt','Width (decimal feet)','number'],['lengthFt','Length (total vehicle feet)','number'],['weightLbs','Gross weight (lb)','number'],['currentWeightLbs','Current weight (lb, optional)','number'],['weightPerAxleLbs','Weight per axle (lb, optional)','number'],['axleCount','Axles','number'],['trailerCount','Trailers','number']] as const;
export function Operations({permissions}:{permissions:string[]}){
 const [drivers,setDrivers]=useState<Driver[]>([]),[fleets,setFleets]=useState<Fleet[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[selected,setSelected]=useState(''),[trucks,setTrucks]=useState<Truck[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const can=(p:string)=>permissions.includes(p);
 async function load(){setError('');try{const [d,f,e]=await Promise.all([can('drivers.read')?api.get<{items:Driver[]}>('/admin/operations/drivers'):Promise.resolve({items:[]}),can('equipment.read')?api.get<{items:Fleet[]}>('/admin/operations/fleets'):Promise.resolve({items:[]}),can('equipment.read')?api.get<{items:Equipment[]}>('/admin/operations/equipment'):Promise.resolve({items:[]})]);setDrivers(d.items);setFleets(f.items);setEquipment(e.items);}catch(e){setError(e instanceof Error?e.message:'Unable to load operations');}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{let live=true;setTrucks([]);if(selected&&can('trucks.read'))api.get<{items:Truck[]}>('/admin/operations/drivers/'+encodeURIComponent(selected)+'/trucks').then(r=>{if(live)setTrucks(r.items);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[selected]);
 async function action(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();setMessage('Saved and audit logged. Truck changes require driver verification.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}
 return <section><h2>Driver and equipment operations</h2><p>Access is limited to your assigned fleets. Measurements are never inferred from equipment names.</p>{error&&<div role="alert" className="error-banner">{error}</div>}{message&&<p role="status">{message}</p>}<button onClick={()=>void load()} disabled={busy}>Refresh</button>
 {can('drivers.read')&&<label>Driver<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.fullName} — {d.email}</option>)}</select></label>}
 {selected&&can('drivers.manage')&&<ReasonAction label={drivers.find(d=>d.id===selected)?.disabledAt?'Restore driver access':'Suspend driver access'} busy={busy} run={why=>action(()=>api.patch('/admin/operations/drivers/'+encodeURIComponent(selected),{disabled:!drivers.find(d=>d.id===selected)?.disabledAt,reason:why}))}/>}
 {trucks.map(t=><TruckEditor key={t.id+':'+t.revision} truck={t} editable={can('trucks.edit')} busy={busy} save={(profile,why)=>action(async()=>{const next=await api.patch<Truck>('/admin/operations/drivers/'+encodeURIComponent(selected)+'/trucks/'+encodeURIComponent(t.id),{expectedRevision:t.revision,profile,reason:why});setTrucks(items=>items.map(item=>item.id===next.id?next:item));})}/>)}
 {can('equipment.read')&&<><h3>Equipment</h3>{equipment.map(e=><article key={e.id} className="account-security-card"><h4>{e.name} · {e.unitNumber}</h4><p>{e.kind==='TRACTOR'?'Tractor':'Trailer'} · Revision {e.revision} · {e.active?'Active':'Inactive'}</p><p>Assigned: {drivers.find(d=>d.id===e.assignedDriverId)?.fullName??(e.assignedDriverId?'Assigned driver':'Unassigned')}</p>{can('equipment.manage')&&<EquipmentAssignment equipment={e} drivers={drivers} busy={busy} save={(driver,active,why)=>action(()=>api.patch('/admin/operations/equipment/'+encodeURIComponent(e.id),{expectedRevision:e.revision,assignedDriverId:driver||null,active,reason:why}))}/>}</article>)}</>}
 {can('equipment.manage')&&<NewEquipment fleets={fleets} busy={busy} save={body=>action(()=>api.post('/admin/operations/equipment',body))}/>}
 {can('roles.manage')&&<FleetManagement fleets={fleets} drivers={drivers} busy={busy} save={(path,body)=>action(()=>api.post('/admin/operations/'+path,body))}/>}
 </section>;
}
function ReasonAction({label,busy,run}:{label:string;busy:boolean;run:(reason:string)=>Promise<void>}){const [why,setWhy]=useState('');return <form onSubmit={e=>{e.preventDefault();void run(why);}}><label>Reason<input minLength={5} maxLength={500} required value={why} onChange={e=>setWhy(e.target.value)}/></label><button disabled={busy}>{label}</button></form>;}
function TruckEditor({truck,editable,busy,save}:{truck:Truck;editable:boolean;busy:boolean;save:(profile:Record<string,unknown>,reason:string)=>Promise<void>}){const [draft,setDraft]=useState<Record<string,unknown>>(truck),[why,setWhy]=useState(''),[confirmed,setConfirmed]=useState(false);return <form className="account-security-card" onSubmit={e=>{e.preventDefault();if(confirmed)void save(draft,why);}}><h3>{truck.name}</h3><p>Revision {truck.revision} · {truck.verificationState.replaceAll('_',' ').toLowerCase()}</p><p>13 ft 6 in = 13.5 feet. Total length includes the complete vehicle combination. Driver must review all changed values.</p><div className="account-form-grid">{fields.map(([key,label,type])=><label key={key}>{label}<input type={type} step={type==='number'?'any':undefined} value={String(draft[key]??'')} disabled={!editable||busy} onChange={e=>{setConfirmed(false);setDraft({...draft,[key]:type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value});}}/></label>)}</div>{editable&&<><label>Reason<input required minLength={5} maxLength={500} value={why} onChange={e=>setWhy(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I reviewed these measured values; this will invalidate the driver's active confirmation.</label><button disabled={busy||!confirmed}>Save for driver review</button></>}</form>;}
function EquipmentAssignment({equipment,drivers,busy,save}:{equipment:Equipment;drivers:Driver[];busy:boolean;save:(driver:string,active:boolean,why:string)=>Promise<void>}){const [driver,setDriver]=useState(equipment.assignedDriverId??''),[active,setActive]=useState(equipment.active),[why,setWhy]=useState('');return <form onSubmit={e=>{e.preventDefault();void save(driver,active,why);}}><label>Assign driver<select value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Unassigned</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.fullName}</option>)}</select></label><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active equipment</label><label>Reason<input value={why} onChange={e=>setWhy(e.target.value)} required minLength={5} maxLength={500}/></label><button disabled={busy}>Save assignment</button></form>;}
function NewEquipment({fleets,busy,save}:{fleets:Fleet[];busy:boolean;save:(body:unknown)=>Promise<void>}){const [fleetId,setFleet]=useState(''),[kind,setKind]=useState('TRACTOR'),[name,setName]=useState(''),[unitNumber,setUnit]=useState(''),[reason,setReason]=useState('');return <form className="account-security-card" onSubmit={e=>{e.preventDefault();void save({fleetId,kind,name,unitNumber,reason});}}><h3>Add equipment</h3><label>Fleet<select required value={fleetId} onChange={e=>setFleet(e.target.value)}><option value="">Choose fleet</option>{fleets.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="TRACTOR">Tractor</option><option value="TRAILER">Trailer</option></select></label><label>Name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Unit number<input required maxLength={40} value={unitNumber} onChange={e=>setUnit(e.target.value)}/></label><label>Reason<input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Add equipment</button></form>;}
function FleetManagement({fleets,drivers,busy,save}:{fleets:Fleet[];drivers:Driver[];busy:boolean;save:(path:string,body:unknown)=>Promise<void>}){const [name,setName]=useState(''),[reason,setReason]=useState(''),[fleetId,setFleet]=useState(''),[userId,setUser]=useState(''),[active,setActive]=useState(true);return <section><h3>Fleet membership</h3><form onSubmit={e=>{e.preventDefault();void save('fleets',{name,reason});}}><label>New fleet name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Reason<input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Create operational fleet</button></form><form onSubmit={e=>{e.preventDefault();void save('fleets/'+encodeURIComponent(fleetId)+'/drivers',{userId,active,reason});}}><label>Fleet<select required value={fleetId} onChange={e=>setFleet(e.target.value)}><option value="">Choose fleet</option>{fleets.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Driver<select required value={userId} onChange={e=>setUser(e.target.value)}><option value="">Choose driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.fullName}</option>)}</select></label><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Member active</label><button disabled={busy||reason.trim().length<5}>Save membership using reason above</button></form></section>;}
