here.user.id = HERE-926b5948-b898-4f4a-8ebd-2ab589da7d63
here.client.id = W3WrlDuCwmzylemg7W93
here.access.key.id = W_NqOVpcfwH_Jth5l9FGkQ
here.access.key.secret = -ehie5I0BBgg-EltrJNFLDSCfhGkqluRY9x_74ozy4MDN5KeGnhNjSt-_U-sxxlmoUth9oHhwvns2zknsxJimA
here.token.endpoint.url = https://account.api.here.com/oauth2/token
