const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),ts=require('typescript');const test=require('node:test'),assert=require('node:assert/strict');
function harness(fetch,fastTimers=false){const source=fs.readFileSync(path.join(__dirname,'../src/api.ts'),'utf8').replace(/import\.meta\.env\.VITE_API_URL/g,JSON.stringify('https://api.example.test'));const exports={};const memory=new Map();const context={exports,fetch,Headers,AbortController,DOMException,URL,window:{setTimeout:fastTimers?(fn)=>setTimeout(fn,5):setTimeout,clearTimeout},sessionStorage:{getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)}};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);return exports;}
for(const status of [400,401,403,404,409,429,500,503])test('Admin HTTP '+status+' hides arbitrary response details',async()=>{const h=harness(async()=>new Response(JSON.stringify({error:{message:'private password stack'}}),{status}));await assert.rejects(()=>h.api.post('/fixture',{}),e=>!String(e.message).match(/private|password|stack/));});
test('Admin refresh does not restore credentials after local logout',async()=>{let release;const gate=new Promise(r=>release=r);const h=harness(async url=>{if(url.endsWith('/auth/refresh')){await gate;return new Response(JSON.stringify({accessToken:'new-fixture',refreshToken:'new-refresh-fixture'}));}return new Response('{}',{status:401});});h.session.save('old-fixture','refresh-fixture');const request=h.api.get('/me').catch(e=>e);await new Promise(r=>setImmediate(r));h.session.clear();release();await request;assert.equal(h.session.access(),null);});
test('Admin transient refresh failure preserves the stored session',async()=>{const h=harness(async url=>new Response('{}',{status:url.endsWith('/auth/refresh')?503:401}));h.session.save('access-fixture','refresh-fixture');await assert.rejects(()=>h.api.get('/me'));assert.equal(h.session.access(),'access-fixture');});

test('Admin response body deadline rejects a stalled body even if fetch ignores abort',async()=>{const h=harness(async()=>({ok:true,status:200,text:()=>new Promise(()=>{})}),true);await assert.rejects(()=>h.api.get('/me'),e=>/too long/.test(e.message));});
test('Admin logout revokes the captured server session and clears local credentials immediately',async()=>{let sent;const h=harness(async(url,init)=>{sent={url,body:JSON.parse(init.body)};return new Response(null,{status:204});});h.session.save('fixture-access','fixture-refresh');const logout=h.signOut();assert.equal(h.session.access(),null);await logout;assert.ok(sent.url.endsWith('/auth/logout'));assert.equal(sent.body.refreshToken,'fixture-refresh');});
test('Admin malformed successful login cannot be stored as a session',async()=>{const h=harness(async()=>new Response(JSON.stringify({accessToken:'fixture',user:{role:'ADMIN'}})));await assert.rejects(()=>h.api.login('fixture@example.test','fixture-password'),e=>e.status===502);assert.equal(h.session.access(),null);});

for(const status of [401,500,503])test('Admin logout '+status+' reports unconfirmed revocation after clearing local credentials',async()=>{
 const h=harness(async()=>new Response(JSON.stringify({error:{message:'private server detail'}}),{status}));
 h.session.save('isolated-access','isolated-refresh');
 await assert.rejects(()=>h.signOut(),e=>e.status===status&&/could not be confirmed/.test(e.message)&&!e.message.includes('private server detail'));
 assert.equal(h.session.access(),null);
});