import {
  automaticResetToken,
  resetToken,
} from '../src/features/auth/resetLink';
const token = 'a'.repeat(64);
test('accepts the fragment credential format generated by the existing recovery email service', () => {
  expect(
    resetToken('https://www.semitrax.com/reset-password.html#token=' + token),
  ).toBe(token);
});
test.each([
  'https://www.semitrax.com.evil.test/reset-password.html',
  'https://evil.test/reset-password.html',
  'http://www.semitrax.com/reset-password.html',
  'https://www.semitrax.com:444/reset-password.html',
  'https://name:password@www.semitrax.com/reset-password.html',
  'https://www.semitrax.com/unrelated',
])('automatic entry refuses unapproved origin/path %s', base => {
  expect(automaticResetToken(base + '#token=' + token)).toBeNull();
});
test.each(['/reset-password', '/reset-password.html'])(
  'automatic entry accepts only approved reset paths %s',
  path => {
    expect(
      automaticResetToken(
        'https://www.semitrax.com' + path + '#token=' + token,
      ),
    ).toBe(token);
  },
);
test('oversized and malformed inputs are rejected', () => {
  expect(resetToken('x'.repeat(5000))).toBeNull();
  expect(automaticResetToken('not-a-url')).toBeNull();
  expect(
    resetToken('https://www.semitrax.com/reset-password#token=bad'),
  ).toBeNull();
  expect(
    resetToken('https://www.semitrax.com/reset-password#token=' + token + '%0A'),
  ).toBeNull();
});
test.each([
  '?token=' + token + '&token=' + token,
  '?token=' + token + '#token=' + 'b'.repeat(64),
  '#token=' + token + '&token=' + token,
])('rejects ambiguous recovery credentials: %s', suffix => {
  expect(
    resetToken('https://www.semitrax.com/reset-password.html' + suffix),
  ).toBeNull();
});
