import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { requireIsolatedDatabase } from './isolatedDatabaseGuard.ts';
const enabled=!!process.env.SUBSCRIPTION_TEST_DATABASE_URL;
let database;
async function db(){process.env.DATABASE_URL=requireIsolatedDatabase(process.env.SUBSCRIPTION_TEST_DATABASE_URL);database??=await import('../dist/lib/prisma.js');return database.prisma;}
after(async()=>{await database?.disconnectDatabase();});
const profile={name:'Isolated measured fixture',tractorType:'Sleeper Cab',trailerType:'Dry Van',trailerCount:1,heightFt:13.5,widthFt:8.5,lengthFt:53,weightLbs:80000,currentWeightLbs:76000,weightPerAxleLbs:17000,axleCount:5,hazmatEnabled:false,hazardousGoods:[],avoidTolls:false,avoidFerries:false,avoidHighways:false,avoidResidential:false,avoidDirtRoads:false};
async function user(p,role='DRIVER'){return p.user.create({data:{email:crypto.randomUUID()+'@example.invalid',fullName:'Isolated fixture',passwordHash:'not-a-real-password-hash',role}});}
test('database stores decimal feet and pounds; administrator change invalidates verification atomically', {skip:!enabled},async()=>{const p=await db();const {saveTruck,verifyTruck,isVerifiedTruck}=await import('../dist/modules/trucks/profileRevision.js');const driver=await user(p);const admin=await user(p,'ADMIN');const created=await saveTruck(p,driver.id,driver.id,profile);assert.equal(created.heightFt,13.5);assert.equal(created.widthFt,8.5);assert.equal(created.weightLbs,80000);assert.equal(isVerifiedTruck(created),false);const verified=await verifyTruck(p,driver.id,created.id,1);assert.equal(verified.isDefault,true);assert.equal(isVerifiedTruck(verified),true);const edited=await saveTruck(p,driver.id,admin.id,{heightFt:14},created.id,1,'Measured fixture correction');assert.equal(edited.revision,2);assert.equal(edited.verificationState,'ADMIN_UPDATED');assert.equal(edited.isDefault,false);assert.equal(isVerifiedTruck(edited),false);await assert.rejects(()=>verifyTruck(p,driver.id,created.id,1),e=>e.safeCode==='TRUCK_PROFILE_CHANGED');const confirmed=await verifyTruck(p,driver.id,created.id,2);assert.equal(isVerifiedTruck(confirmed),true);const audit=await p.adminAuditLog.findMany({where:{targetId:created.id}});assert.equal(audit.length,4);assert.ok(audit.some(a=>a.actorUserId===admin.id&&a.action==='TRUCK_UPDATED'));});
test('database rejects cross-owner confirmation and invalid units without mutation', {skip:!enabled},async()=>{const p=await db();const {saveTruck,verifyTruck}=await import('../dist/modules/trucks/profileRevision.js');const a=await user(p),b=await user(p);const t=await saveTruck(p,a.id,a.id,profile);await assert.rejects(()=>verifyTruck(p,b.id,t.id,1),e=>e.safeStatus===404);const audits=await p.adminAuditLog.count({where:{targetId:t.id}});await assert.rejects(()=>saveTruck(p,a.id,a.id,{heightFt:162},t.id,1));assert.equal((await p.truck.findUniqueOrThrow({where:{id:t.id}})).revision,1);assert.equal(await p.adminAuditLog.count({where:{targetId:t.id}}),audits);});
test('database concurrent edits cannot silently overwrite reviewed revision', {skip:!enabled},async()=>{const p=await db();const {saveTruck}=await import('../dist/modules/trucks/profileRevision.js');const a=await user(p);const t=await saveTruck(p,a.id,a.id,profile);const outcomes=await Promise.allSettled([saveTruck(p,a.id,a.id,{heightFt:14},t.id,1),saveTruck(p,a.id,a.id,{heightFt:14.5},t.id,1)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal((await p.truck.findUniqueOrThrow({where:{id:t.id}})).revision,2);});
test('database revocation immediately invalidates access-session ownership and suspension', {skip:!enabled},async()=>{const p=await db();const {currentAccessSession}=await import('../dist/services/accessSession.js');const a=await user(p);const s=await p.refreshToken.create({data:{userId:a.id,tokenHash:crypto.randomBytes(32).toString('hex'),expiresAt:new Date(Date.now()+60000)}});const claims={userId:a.id,sessionId:s.id};assert.equal((await currentAccessSession(p,claims)).id,a.id);assert.equal(await currentAccessSession(p,{...claims,userId:'someone-else'}),null);await p.refreshToken.update({where:{id:s.id},data:{revokedAt:new Date()}});assert.equal(await currentAccessSession(p,claims),null);});
test('database fleet scope denies nonmembers and immediately applies staff demotion', {skip:!enabled},async()=>{const p=await db();const {operationalActor,requireDriver,requirePermission}=await import('../dist/modules/admin/operationalPolicy.js');const staff=await user(p),driver=await user(p),other=await user(p);const fleet=await p.operationalFleet.create({data:{name:'Isolated fleet'}});const grant=await p.staffAccess.create({data:{userId:staff.id,role:'OPERATIONS',fleets:{create:{fleetId:fleet.id}}}});await p.operationalFleetDriver.create({data:{userId:driver.id,fleetId:fleet.id}});const actor=await operationalActor(p,{userId:staff.id,role:staff.role});await requireDriver(p,actor,driver.id);await assert.rejects(()=>requireDriver(p,actor,other.id));await p.staffAccess.update({where:{id:grant.id},data:{role:'READ_ONLY'}});const current=await operationalActor(p,{userId:staff.id,role:staff.role});assert.throws(()=>requirePermission(current,'trucks.edit'));});
