import { RouteStore } from '../src/features/routing/RouteStore';
import { TruckProfileStore } from '../src/features/truckProfile/TruckProfileStore';
import { isServerVerifiedTruck, serializeTruck, parseTruckRoute } from '../src/models/contracts';
import { TruckRoutingService } from '../src/services/routing/TruckRoutingService';
import { StopPlan } from '../src/features/stops/StopPlan';
import type { ApiClient } from '../src/services/api/ApiClient';
import { truck, routeRaw } from './fixtures';
test('revision metadata never enters provider dimensions',()=>{const payload=serializeTruck(truck,true);for(const key of ['revision','verifiedRevision','verifiedAt','verificationState'])expect(payload).not.toHaveProperty(key);});
test.each([{revision:undefined},{verifiedRevision:2},{verifiedAt:null},{verificationState:'ADMIN_UPDATED' as const},{isDefault:false}])('unverified server metadata cannot permit routing: %j',change=>{expect(isServerVerifiedTruck({...truck,...change})).toBe(false);});
test('server revision changes invalidate locally reviewed truck even when dimensions stay identical',async()=>{let profile={...truck,lengthFt:53};const request=jest.fn(async(method:string)=>method==='GET'?{items:[profile]}:undefined);const store=new TruckProfileStore({request} as unknown as ApiClient,jest.fn());await store.load();await store.select(profile);expect(request).toHaveBeenCalledWith('POST','/trucks/'+truck.id+'/verify',{expectedRevision:1});profile={...profile,revision:2};await store.load();expect(store.getSnapshot().selected).toBeNull();});
test('unverified legacy profile cannot send route request',async()=>{const request=jest.fn();const service=new TruckRoutingService({request} as unknown as ApiClient);await expect(service.calculate({lat:40,lng:-100},{destination:{lat:40.1,lng:-100},stops:[]} as unknown as StopPlan,{...truck,revision:undefined})).rejects.toThrow();expect(request).not.toHaveBeenCalled();});
test('nested malformed legs and alternative shapes cannot pass the route boundary',()=>{for(const change of [{legs:[{opaque:'data'}]},{alternatives:[{routeGeometry:'bad'}]},{legs:[{distanceMiles:1,durationSeconds:60,geometry:[],maneuvers:[routeRaw.turnByTurn[0]]}]}])expect(()=>parseTruckRoute({...routeRaw,...change})).toThrow();});

test('a server profile conflict removes an old route instead of retaining a stale preview',async()=>{let fail=false;const invalidated=jest.fn();const routes=new RouteStore({calculate:async()=>{if(fail)throw {code:'TRUCK_PROFILE_CHANGED',status:409};return parseTruckRoute(routeRaw);}} as unknown as TruckRoutingService,invalidated);const plan={destination:{lat:40.1,lng:-100},stops:[]} as unknown as StopPlan;expect(await routes.calculate({lat:40,lng:-100},plan,truck)).toBe(true);fail=true;expect(await routes.calculate({lat:40,lng:-100},plan,truck)).toBe(false);expect(routes.getSnapshot().route).toBeNull();expect(routes.getSnapshot().error).toContain('profile changed');expect(invalidated).toHaveBeenCalledTimes(1);});
